### ISSUE TITLE
Advance?

### ISSUE THREAD

**Issue by fda77** [MohammadAG/Xposed-Always-Expandable-Notifications#1]
Hello, what's the advantage of this against http://repo.xposed.info/module/com.ugglynoodle.allnotificationsexpanded ?

**Comment by MohammadAG** [comment]
Different goals altogether. That module forces all expandable notifications to be expanded. That requires the notification itself be expandable in the first place. This module forces all notifications that aren't expandable to be expandable, but you still have to expand them yourself.

Basically, this fixes apps still stuck in ICS.

**Comment by fda77** [comment]
Thx!
